/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import inventario.Conexion;
import inventario.Producto;
import static inventario.Producto.formatearDecimales;
import inventario.ProductoData;
import inventario.ProductoPerecedero;
import inventario.ProductoPerecederoData;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Popa
 */
public class Principal extends javax.swing.JInternalFrame {
     private Conexion conexion;
     private ProductoData productoData;
     private ProductoPerecederoData productoPerecederoData;
     

    /**
     * Creates new form Principal
     */
    public Principal() {
        
             initComponents();
              try {
                  
             conexion = new Conexion();
             productoData = new ProductoData(conexion);
             productoPerecederoData = new ProductoPerecederoData(conexion);
            
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
         }
        ocultarTitulo();
             vencimiento.setVisible(false); 
             venc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        fondo = new javax.swing.JPanel();
        pestañas = new javax.swing.JTabbedPane();
        venta = new javax.swing.JPanel();
        salir2 = new javax.swing.JButton();
        ganancia1 = new javax.swing.JPanel();
        salir1 = new javax.swing.JButton();
        producto1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        marca1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        codigo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pFinal1 = new javax.swing.JTextField();
        guardar1 = new javax.swing.JButton();
        editar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lista = new javax.swing.JPanel();
        salir3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        producto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ganancia = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        venc = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        si = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        salir = new javax.swing.JButton();
        vencimiento = new com.toedter.calendar.JDateChooser();
        calcular = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        escritorio.setPreferredSize(new java.awt.Dimension(500, 700));

        fondo.setBackground(new java.awt.Color(153, 153, 153));
        fondo.setPreferredSize(new java.awt.Dimension(500, 700));

        pestañas.setBackground(new java.awt.Color(0, 0, 0));
        pestañas.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        venta.setBackground(new java.awt.Color(204, 204, 255));
        venta.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        salir2.setBackground(new java.awt.Color(204, 204, 255));
        salir2.setIcon(new javax.swing.ImageIcon("D:\\icon\\shield.png")); // NOI18N

        ganancia1.setBackground(new java.awt.Color(204, 204, 255));
        ganancia1.setPreferredSize(new java.awt.Dimension(500, 573));

        salir1.setBackground(new java.awt.Color(204, 204, 255));
        salir1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        salir1.setText("Salir");
        salir1.setToolTipText("");

        producto1.setToolTipText("Obligatorio");
        producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel11.setText("Producto");

        jLabel12.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel12.setText("Marca");

        marca1.setToolTipText("Obligatorio");
        marca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel13.setText("Codigo");

        codigo1.setToolTipText("Ingrese Codigo");

        jLabel15.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel15.setText("Precio ");

        pFinal1.setToolTipText("Opcional");
        pFinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pFinal1ActionPerformed(evt);
            }
        });

        guardar1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        guardar1.setText("Guardar");

        editar1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        editar1.setText("Editar");

        jScrollPane2.setViewportView(jList1);

        jLabel20.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel20.setText("Total");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ganancia1Layout = new javax.swing.GroupLayout(ganancia1);
        ganancia1.setLayout(ganancia1Layout);
        ganancia1Layout.setHorizontalGroup(
            ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ganancia1Layout.createSequentialGroup()
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ganancia1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)))
                    .addGroup(ganancia1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(guardar1)
                        .addGap(42, 42, 42)
                        .addComponent(editar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ganancia1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton4)
                        .addGap(40, 40, 40)
                        .addComponent(salir1))
                    .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(producto1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(pFinal1)
                        .addComponent(marca1)
                        .addComponent(codigo1)))
                .addGap(57, 57, 57))
            .addGroup(ganancia1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ganancia1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        ganancia1Layout.setVerticalGroup(
            ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ganancia1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(producto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(ganancia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar1)
                    .addComponent(editar1)
                    .addComponent(jButton4)
                    .addComponent(salir1))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout ventaLayout = new javax.swing.GroupLayout(venta);
        venta.setLayout(ventaLayout);
        ventaLayout.setHorizontalGroup(
            ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                .addGap(0, 470, Short.MAX_VALUE)
                .addComponent(salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(ganancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ventaLayout.setVerticalGroup(
            ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                .addGap(0, 562, Short.MAX_VALUE)
                .addComponent(salir2))
            .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(ganancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pestañas.addTab("Registrar Venta", venta);

        lista.setBackground(new java.awt.Color(204, 204, 255));

        salir3.setBackground(new java.awt.Color(204, 204, 255));
        salir3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        salir3.setText("Salir");

        listado.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca", "Tipo", "Costo", "Precio Final ", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listado);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel10.setText("Buscar");

        jButton1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\icon\\search.png")); // NOI18N

        jButton3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton3.setText("Limpiar");

        javax.swing.GroupLayout listaLayout = new javax.swing.GroupLayout(lista);
        lista.setLayout(listaLayout);
        listaLayout.setHorizontalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(listaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(112, 112, 112)
                .addComponent(salir3)
                .addGap(156, 156, 156))
        );
        listaLayout.setVerticalGroup(
            listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir3)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pestañas.addTab("Lista de Productos", lista);

        panel.setBackground(new java.awt.Color(204, 204, 255));

        cerrar.setBackground(new java.awt.Color(204, 204, 255));
        cerrar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cerrar.setText("Salir");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        producto.setToolTipText("Obligatorio");
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setText("Producto");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("Marca");

        Marca.setToolTipText("Obligatorio");
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("Codigo");

        Codigo.setToolTipText("Obligatorio");

        jLabel4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel4.setText("Precio Costo");

        costo.setText("0.00");
        costo.setToolTipText("Obligatorio");
        costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setText("Precio Final");

        pFinal.setText("0.00");
        pFinal.setToolTipText("Opcional");
        pFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pFinalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setText("Stock");

        stock.setToolTipText("Obligatorio");

        jLabel7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel7.setText("Ganancia %");

        Ganancia.setText("0");
        Ganancia.setToolTipText("Opcional");

        guardar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        venc.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        venc.setText("Vencimiento");

        jLabel9.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel9.setText("Perecedero?");

        si.setText("si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        no.setText("no");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        salir.setText("Limpiar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        calcular.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon("D:\\icon\\search2.png")); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(no)
                .addGap(53, 53, 53)
                .addComponent(si)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(guardar)
                .addGap(28, 28, 28)
                .addComponent(editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(29, 29, 29)
                .addComponent(cerrar)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(venc)
                    .addComponent(jLabel5))
                .addGap(68, 68, 68)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(stock, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(costo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Marca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(producto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(vencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(pFinal)
                            .addGap(18, 18, 18)
                            .addComponent(calcular)))
                    .addComponent(Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(si)
                    .addComponent(no))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscar))
                .addGap(17, 17, 17)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular))
                .addGap(42, 42, 42)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(venc)
                    .addComponent(vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(editar)
                    .addComponent(cerrar)
                    .addComponent(salir))
                .addGap(38, 38, 38))
        );

        pestañas.addTab("Registrar Producto", panel);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañas)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañas)
        );

        escritorio.setLayer(fondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);
        escritorio.setBounds(0, 0, 500, 674);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void pFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pFinalActionPerformed

    private void producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto1ActionPerformed

    private void marca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca1ActionPerformed

    private void pFinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pFinal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pFinal1ActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        no.setSelected(false);
         vencimiento.setVisible(true);
         venc.setVisible(true);
         setConfiguracionJDateChooser(); 
    }//GEN-LAST:event_siActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       if (producto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Producto no puede estar vacio ");
        }else if (Marca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Marca no puede estar vacio ");
        } else if (Codigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Codigo no puede estar vacio ");
        }else if (!validarCampoNumEntero(Codigo.getText())) {
                JOptionPane.showMessageDialog(null, "Codigo solo ingrese valores numéricos");
        }else if (costo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Precio Costo no puede estar vacio ");
        }else if (!validarCampoPrecio(costo.getText())) {
                JOptionPane.showMessageDialog(null, "Precio Costo solo ingrese valores numéricos");
        }else if (!validarCampoNumEntero(Ganancia.getText())) {
                JOptionPane.showMessageDialog(null, "Ganancia solo ingrese valores numéricos");
        }else if (!validarCampoPrecio(pFinal.getText())) {
                JOptionPane.showMessageDialog(null, "Precio Final solo ingrese valores numéricos");
        } else if (stock.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, " Stock no puede estar vacio ");
        }else if (!validarCampoNumEntero(stock.getText())) {
                JOptionPane.showMessageDialog(null, "Stock solo ingrese valores numéricos");
        }else{
           if(si.isSelected()){  
        LocalDate fechaVencimiento = formatearFecha(vencimiento.getDate());
        String codigo = Codigo.getText();
        String marca = Marca.getText();
        String tipo = producto.getText();
        double precioCosto = Double.parseDouble(costo.getText());
        int porcentajeGanancia = Integer.parseInt(Ganancia.getText());
        double precioFinal = Double.parseDouble(pFinal.getText());
        int Stock = Integer.parseInt (stock.getText());
            if (!productoPerecederoData.isCodigoExistenteP(codigo)){
         ProductoPerecedero productoP = new ProductoPerecedero(fechaVencimiento,codigo,marca,tipo,precioCosto,precioFinal,Stock,porcentajeGanancia );  
         productoPerecederoData.guardarProductoPerecedero(productoP);
          JOptionPane.showMessageDialog(null, "Producto guardado");
           }else{
            JOptionPane.showMessageDialog(null, " El producto ya existe ");    
            }
           }else{
        String codigo = Codigo.getText();
        String marca = Marca.getText();
        String tipo = producto.getText();
        double precioCosto = Double.parseDouble(costo.getText());
        int porcentajeGanancia = Integer.parseInt(Ganancia.getText()); 
        double precioFinal = Double.parseDouble(pFinal.getText());
        int Stock = Integer.parseInt (stock.getText());
          if (!productoData.isCodigoExistente(codigo)){  
          Producto produc = new Producto (codigo,marca,tipo,precioCosto,precioFinal,Stock,porcentajeGanancia);
         productoData.guardarProducto(produc);
         JOptionPane.showMessageDialog(null, "Producto guardado");
            } else{
           JOptionPane.showMessageDialog(null, " El producto ya existe ");     
          }  
 }
      } 
       
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
       si.setSelected(false);
        vencimiento.setVisible(false);
        venc.setVisible(false);
    }//GEN-LAST:event_noActionPerformed

    private void costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoActionPerformed
        pFinal.setText(title);
    }//GEN-LAST:event_costoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        campoPrecio();
    }//GEN-LAST:event_calcularActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
       if (!validarCampoNumEntero(Codigo.getText())) {
                JOptionPane.showMessageDialog(null, "Codigo solo ingrese valores numéricos");
        }else{
        String codigo = Codigo.getText();
        Producto produc = productoData.buscarProducto(codigo);
       if (produc != null) {
          int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere guardar los cambios?", "Alerta!", JOptionPane.YES_NO_OPTION);
      if (resp != 1) {
        produc.setCodigo(Codigo.getText());
        produc.setMarca(Marca.getText());
        produc.setTipo(producto.getText());
        produc.setPrecioCosto(Double.parseDouble(costo.getText()));
        produc.setPorcentajeGanancia(Integer.parseInt(Ganancia.getText())); 
        produc.setPrecioFinal(Double.parseDouble(pFinal.getText()));
        produc.setStock(Integer.parseInt (stock.getText())); 
         productoData.editarProducto(produc);
         JOptionPane.showMessageDialog(null, " Datos editados! ");
        }
      }else{
        ProductoPerecedero producP = productoPerecederoData.buscarProductoPerecedero(codigo);
      if (producP != null) {
          int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere guardar los cambios?", "Alerta!", JOptionPane.YES_NO_OPTION);
      if (resp != 1) {
        producP.setFechaVencimiento(formatearFecha(vencimiento.getDate()));
        producP.setCodigo(Codigo.getText());
        producP.setMarca(Marca.getText());
        producP.setTipo(producto.getText());
        producP.setPrecioCosto(Double.parseDouble(costo.getText()));
        producP.setPorcentajeGanancia(Integer.parseInt(Ganancia.getText())); 
        producP.setPrecioFinal(Double.parseDouble(pFinal.getText()));
        producP.setStock(Integer.parseInt (stock.getText())); 
         productoPerecederoData.editarProductoPerecedero(producP);
         JOptionPane.showMessageDialog(null, " Datos editados! ");
      }
       }else{
          JOptionPane.showMessageDialog(null, "El codigo ingresado no existe ");
      }
      }
       }
    }//GEN-LAST:event_editarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       producto.setText("");
       no.isSelected();
       Marca.setText("");
       Codigo.setText("");
       costo.setText(String.valueOf(0.00));
       Ganancia.setText(String.valueOf(0));
       stock.setText("");
       pFinal.setText(String.valueOf(0.00));
       setConfiguracionJDateChooser();
    }//GEN-LAST:event_salirActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
     String codigo = Codigo.getText();
        Producto produc = productoData.buscarProducto(codigo);
       if (produc != null) {
       producto.setText(produc.getTipo());
       Marca.setText(produc.getMarca());
       costo.setText(String.valueOf(produc.getPrecioCosto()));
       Ganancia.setText(String.valueOf(produc.getPorcentajeGanancia()));
       stock.setText(String.valueOf(produc.getStock()));
       pFinal.setText(String.valueOf(produc.getPrecioFinal())); 
       }else{
       ProductoPerecedero prodp = productoPerecederoData.buscarProductoPerecedero(codigo);
       if(prodp != null){
       producto.setText(prodp.getTipo());
       Marca.setText(prodp.getMarca());
       costo.setText(String.valueOf(prodp.getPrecioCosto()));
       Ganancia.setText(String.valueOf(prodp.getPorcentajeGanancia()));
       stock.setText(String.valueOf(prodp.getStock()));
       pFinal.setText(String.valueOf(prodp.getPrecioFinal()));
       vencimiento.setVisible(true);
         venc.setVisible(true);
       Date date = java.sql.Date.valueOf(prodp.getFechaVencimiento());
       vencimiento.setDate(date);
        }else{
          JOptionPane.showMessageDialog(null, "El codigo ingresado no existe ");  
        }
           
       }
    }//GEN-LAST:event_buscarActionPerformed
 private boolean validarCampoPrecio(String value) {
        try {
            double num = Double.parseDouble(value);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }
 private boolean validarCampoNumEntero(String value) {
        try {
            int num = Integer.parseInt(value);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }
  public LocalDate formatearFecha(Date date) {
        SimpleDateFormat formato = new SimpleDateFormat("YYYY-MM-dd");
        LocalDate fechaFormateada = LocalDate.parse(formato.format(date));
        return fechaFormateada;
    }
  public void setConfiguracionJDateChooser() {
        // Setea fecha actual
        Calendar toDay = new GregorianCalendar();
        vencimiento.setCalendar(toDay);
        
        // Setea fecha mínima
        vencimiento.setMinSelectableDate(toDay.getTime());
        
        // Desactiva edición y carga manual de fechas
        //((JTextField) this.vencimiento.getDateEditor()).setEditable(false);
        }
  public void ocultarTitulo(){
 BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();   
 bi.setNorthPane(null);
 
}
  public void campoPrecio(){
        int porcentajeGanancia = Integer.parseInt(Ganancia.getText());
        double precioCosto = Double.parseDouble(costo.getText());
     double precio = formatearDecimales(precioCosto+(precioCosto*porcentajeGanancia/100),2);
     pFinal.setText(String.valueOf(precio));
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Ganancia;
    private javax.swing.JTextField Marca;
    private javax.swing.JButton buscar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField codigo1;
    private javax.swing.JTextField costo;
    private javax.swing.JButton editar;
    private javax.swing.JButton editar1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel ganancia1;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel lista;
    private javax.swing.JTable listado;
    private javax.swing.JTextField marca1;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField pFinal;
    private javax.swing.JTextField pFinal1;
    private javax.swing.JPanel panel;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JTextField producto;
    private javax.swing.JTextField producto1;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JButton salir2;
    private javax.swing.JButton salir3;
    private javax.swing.JRadioButton si;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel venc;
    private com.toedter.calendar.JDateChooser vencimiento;
    private javax.swing.JPanel venta;
    // End of variables declaration//GEN-END:variables
}
